<?php

use Illuminate\Database\Seeder;

class Card_imgsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('card_imgs')->insert([
            'card_id'=>1,
             'img_path'=>'(1).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>1,
             'img_path'=>'(2).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>1,
             'img_path'=>'(3).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>1,
             'img_path'=>'(4).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>2,
             'img_path'=>'(5).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>2,
             'img_path'=>'(6).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>2,
             'img_path'=>'(7).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>2,
             'img_path'=>'(8).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>2,
             'img_path'=>'(9).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>3,
             'img_path'=>'(10).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>3,
             'img_path'=>'(11).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>3,
             'img_path'=>'(12).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>3,
             'img_path'=>'(13).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>4,
             'img_path'=>'(14).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>4,
             'img_path'=>'(15).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>4,
             'img_path'=>'(16).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>4,
             'img_path'=>'(17).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>5,
             'img_path'=>'(18).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>5,
             'img_path'=>'(19).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>5,
             'img_path'=>'(20).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>5,
             'img_path'=>'(21).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>6,
             'img_path'=>'(22).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>6,
             'img_path'=>'(23).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>6,
             'img_path'=>'(24).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>6,
             'img_path'=>'(25).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>6,
             'img_path'=>'(26).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>6,
             'img_path'=>'(27).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>7,
             'img_path'=>'(28).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>7,
             'img_path'=>'(29).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>7,
             'img_path'=>'(30).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>7,
             'img_path'=>'(31).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>7,
             'img_path'=>'(32).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>8,
             'img_path'=>'(33).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>8,
             'img_path'=>'(34).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>8,
             'img_path'=>'(35).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>8,
             'img_path'=>'(36).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>9,
             'img_path'=>'(37).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>9,
             'img_path'=>'(38).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>9,
             'img_path'=>'(39).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>9,
             'img_path'=>'(40).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>10,
             'img_path'=>'(41).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>10,
             'img_path'=>'(42).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>10,
             'img_path'=>'(43).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>10,
             'img_path'=>'(44).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>11,
             'img_path'=>'(45).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>11,
             'img_path'=>'(46).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>11,
             'img_path'=>'(47).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>11,
             'img_path'=>'(48).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>11,
             'img_path'=>'(49).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>11,
             'img_path'=>'(50).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>11,
             'img_path'=>'(51).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>12,
             'img_path'=>'(52).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>12,
             'img_path'=>'(53).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>12,
             'img_path'=>'(54).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>13,
             'img_path'=>'(55).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>13,
             'img_path'=>'(56).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>13,
             'img_path'=>'(57).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>13,
             'img_path'=>'(58).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>14,
             'img_path'=>'(59).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>14,
             'img_path'=>'(60).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>14,
             'img_path'=>'(61).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>14,
             'img_path'=>'(62).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>15,
             'img_path'=>'(63).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>15,
             'img_path'=>'(64).JPG'
        ]);
        DB::table('card_imgs')->insert([
            'card_id'=>15,
             'img_path'=>'(65).JPG'
        ]);
        
    }
}
